version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - laravel_vendor:/var/www/vendor
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
            - "8000:8000"
            - "9003:9003"
        command: ["/bin/sh", "/var/www/docker/app/start-container.sh"]
        extra_hosts:
        - "host.docker.internal:host-gateway"
        depends_on:
            mysql:
                condition: service_healthy

    frontend:
        image: node:20-bullseye
        container_name: laravel_frontend
        working_dir: /var/www
        environment:
            CHOKIDAR_USEPOLLING: 'true'
            VITE_PORT: 5173
            VITE_DEV_SERVER_URL: http://localhost:5173
            VITE_HMR_HOST: localhost
            VITE_HMR_CLIENT_PORT: 5173
        volumes:
            - .:/var/www
            - frontend_node_modules:/var/www/node_modules
        ports:
            - "5173:5173"
        command: ["/bin/sh", "/var/www/docker/frontend/start-container.sh"]
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            retries: 10
            timeout: 5s

volumes:
    db_data:
    laravel_vendor:
    frontend_node_modules:
